// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzWb2JnuP7K05Qjc3okhCCt9j8t9pae5w',
    appId: '1:457935623953:web:7edf259712252dd83adeb0',
    messagingSenderId: '457935623953',
    projectId: 'hydroai-53e89',
    authDomain: 'hydroai-53e89.firebaseapp.com',
    databaseURL:
        'https://hydroai-53e89-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'hydroai-53e89.appspot.com',
    measurementId: 'G-HX1Z0R7XWV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkO_mQUFaISrwTrSJp_-Bg4qTT9wOwE3c',
    appId: '1:457935623953:android:7959f96a5c1d40d73adeb0',
    messagingSenderId: '457935623953',
    projectId: 'hydroai-53e89',
    databaseURL:
        'https://hydroai-53e89-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'hydroai-53e89.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBc1wFkRietURlwladNl68HGmDR-fPQYRw',
    appId: '1:457935623953:ios:4fb126385cec92753adeb0',
    messagingSenderId: '457935623953',
    projectId: 'hydroai-53e89',
    databaseURL:
        'https://hydroai-53e89-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'hydroai-53e89.appspot.com',
    iosBundleId: 'com.example.hydroAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBc1wFkRietURlwladNl68HGmDR-fPQYRw',
    appId: '1:457935623953:ios:4fb126385cec92753adeb0',
    messagingSenderId: '457935623953',
    projectId: 'hydroai-53e89',
    databaseURL:
        'https://hydroai-53e89-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'hydroai-53e89.appspot.com',
    iosBundleId: 'com.example.hydroAi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBzWb2JnuP7K05Qjc3okhCCt9j8t9pae5w',
    appId: '1:457935623953:web:0d25fc1b17eb8b2f3adeb0',
    messagingSenderId: '457935623953',
    projectId: 'hydroai-53e89',
    authDomain: 'hydroai-53e89.firebaseapp.com',
    databaseURL:
        'https://hydroai-53e89-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'hydroai-53e89.appspot.com',
    measurementId: 'G-Q8FX7K7YRY',
  );
}
